Rewrite of mono_wasm_invoke_js routine from native interface for executing javascript.
From the official documentation:  http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html
Emscripten provides two main approaches for calling JavaScript from C/C++: running the script using emscripten_run_script() or writing “inline JavaScript”.

Each of these ways will return `TypeError: eval is not a function` when being executed from Node.js/Electron.  This needed to be replaced so added a hook in the `library-mono.js` file that can be called from monoembedding native interface.  This should also allow doing a `require(...)` in the JavaScript code being passed where using a simple `eval` as described above would execute in their own context and not have access to the Node.js `require(...)`.

- Any calls to ExecuteJavaScript must return an instance of a JavaScript function.  If not they will be presented with the error: `Node.js code must return an instance of a JavaScript function.  Please use `return` statement to return a function.`  See example below.
- Add a couple of helper routines to Runtime interface that uses a MiniJSON version for Deserializing and Serializing JSON.  These are quick simple routines and developers may need to use a more advanced Json package.  See the source code for usage examples.

Example of ExecuteJavaScript call:

                    try
                    {
                        Runtime.ExecuteJavaScript("return function () { document.getElementById ('myelement').disabled = false; };");
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine($"initialize exception: {e.Message}");
                    }